language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - SYMFONY_VERSION="1.*"

before_script:
  - composer self-update
  - composer --version
  - composer require ifthenpay/omnipay-ifthenpay:${IFTHENPAY_VERSION} --no-update

script: composer install -n --dev --prefer-source